### ISSUE TITLE
ImportError: cannot import name S3Auth

### ISSUE THREAD

**Issue by roflmao** [ceph/ceph-nagios-plugins#55]
Installed requests-aws:

```
Successfully installed requests-aws-0.1.8
Successfully installed awsauth-0.3.3
```

```
$ ./check_ceph_rgw_api 
Traceback (most recent call last):
  File "./check_ceph_rgw_api", line 24, in <module>
    from awsauth import S3Auth
ImportError: cannot import name S3Auth
```
running ubuntu 16.04:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
```

**Comment by valerytschopp** [comment]
Hi @roflmao 

Please uninstall `awsauth`, this package is not needed, and not the correct one. Uninstall like this:

```
ubuntu@ubuntu-16:~/ceph-nagios-plugins/src$ ./check_ceph_rgw_api 
Traceback (most recent call last):
  File "./check_ceph_rgw_api", line 24, in <module>
    from awsauth import S3Auth
ImportError: cannot import name S3Auth

ubuntu@ubuntu-16:~/ceph-nagios-plugins/src$ sudo pip uninstall awsauth
Found existing installation: awsauth 0.3.3
Uninstalling awsauth-0.3.3:
  Would remove:
    /usr/local/bin/awsauth.py
    /usr/local/lib/python2.7/dist-packages/awsauth-0.3.3-py2.7.egg-info
    /usr/local/lib/python2.7/dist-packages/awsauth/*
Proceed (y/n)? y
  Successfully uninstalled awsauth-0.3.3

ubuntu@ubuntu-16:~/ceph-nagios-plugins/src$ ./check_ceph_rgw_api 
usage: check_ceph_rgw_api [-h] -H HOST [-k] [-e ADMIN_ENTRY] -a ACCESS_KEY -s
                          SECRET_KEY [-d] [-b] [-v]
check_ceph_rgw_api: error: argument -H/--host is required
```
