### ISSUE TITLE
check_ceph_df: `TypeError: a bytes-like object is required, not 'str'`

### ISSUE THREAD

**Issue by lorenzbausch** [ceph/ceph-nagios-plugins#70]
When monitoring a specific pool with `check_ceph_df` the following error is thrown:
```bash
$ ./check_ceph_df --pool rbd -C 70 -W 50
Traceback (most recent call last):
  File "/usr/lib64/nagios/plugins/ceph-nagios-plugins/check_ceph_df", line 231, in <module>
    sys.exit(main())
  File "/usr/lib64/nagios/plugins/ceph-nagios-plugins/check_ceph_df", line 136, in main
    if args.pool in line:
TypeError: a bytes-like object is required, not 'str'
```
```bash
$ /usr/bin/env python -V
Python 3.6.8
```

I worked around this by modifying line 136:
```python
# before
if args.pool in line:

# after
if args.pool in str(line):
```
Not sure if this an appropriate fix - if so, I can open a PR to fix this issue.

**Comment by valerytschopp** [comment]
Feel free to open a PR
